(() => {
  const KEY = 'meeting-notes-v1';
  const $ = id => document.getElementById(id);
  const state = { recording:false, paused:false, startedAt:0, elapsed:0, timer:null, finalText:'', interim:'', recognition:null };
  const title = $('meetingTitle'), transcript = $('transcript'), statusPill = $('statusPill'), statusText = $('statusText');
  const supported = 'SpeechRecognition' in window || 'webkitSpeechRecognition' in window;
  const getRecords = () => JSON.parse(localStorage.getItem(KEY) || '[]');
  const saveRecords = records => localStorage.setItem(KEY, JSON.stringify(records));
  const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function renderText(){ const text = (state.finalText + (state.interim ? (state.finalText ? '\n' : '') + state.interim : '')).trim(); transcript.innerHTML = text ? esc(text).replace(/\n/g,'<br>') : '<div class="empty-state"><span>◌</span><p>点击“开始记录”，这里会显示实时转写内容</p></div>'; $('wordCount').textContent = `${text.replace(/\s/g,'').length} 字`; }
  function setStatus(kind, text){ statusPill.className = `status-pill ${kind}`; statusText.textContent = text; }
  function formatTime(seconds){ const h=String(Math.floor(seconds/3600)).padStart(2,'0'), m=String(Math.floor(seconds%3600/60)).padStart(2,'0'), s=String(Math.floor(seconds%60)).padStart(2,'0'); return `${h}:${m}:${s}`; }
  function tick(){ state.elapsed = (Date.now()-state.startedAt)/1000; $('timer').textContent = formatTime(state.elapsed); }
  function setupRecognition(){ if(!supported) return null; const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; const r = new Recognition(); r.continuous=true; r.interimResults=true; r.lang='zh-CN'; r.onresult=e=>{ state.interim=''; for(let i=e.resultIndex;i<e.results.length;i++){ const chunk=e.results[i][0].transcript; if(e.results[i].isFinal) state.finalText += chunk+' '; else state.interim += chunk; } renderText(); }; r.onerror=e=>{ if(e.error==='not-allowed') showToast('浏览器未授予麦克风权限'); else if(e.error!=='aborted') showToast('语音识别暂时不可用'); }; r.onend=()=>{ if(state.recording&&!state.paused) try{r.start()}catch(_){} }; return r; }
  function start(){ if(!supported){showToast('当前浏览器不支持语音识别，请使用 Chrome 或 Edge'); return} if(!state.recognition) state.recognition=setupRecognition(); state.recording=true; state.paused=false; state.startedAt=Date.now()-state.elapsed*1000; state.timer ||= setInterval(tick,250); try{state.recognition.start()}catch(_){} $('startBtn').disabled=true; $('pauseBtn').disabled=false; $('stopBtn').disabled=false; setStatus('recording','正在记录'); }
  function pause(){ state.paused=true; state.recording=false; state.recognition?.stop(); clearInterval(state.timer); state.timer=null; $('startBtn').disabled=false; $('startBtn').textContent='▶ 继续记录'; $('pauseBtn').disabled=true; setStatus('paused','已暂停'); }
  function stop(save=true){ state.recording=false; state.paused=false; state.recognition?.stop(); clearInterval(state.timer); state.timer=null; tick(); if(save && state.finalText.trim()){ const records=getRecords(); records.unshift({id:Date.now(),title:title.textContent.trim()||'未命名会议',text:state.finalText.trim(),duration:Math.round(state.elapsed),createdAt:new Date().toISOString()}); saveRecords(records); renderHistory(); showToast('会议记录已保存'); } $('startBtn').disabled=false; $('startBtn').textContent='● 开始记录'; $('pauseBtn').disabled=true; $('stopBtn').disabled=true; setStatus('idle','准备就绪'); }
  function newMeeting(){ if(state.recording||state.finalText.trim()){ if(!confirm('当前记录尚未保存，确定新建会议吗？')) return; } stop(false); state.finalText='';state.interim='';state.elapsed=0;$('timer').textContent='00:00:00';title.textContent='未命名会议';renderText(); }
  function renderHistory(){ const query=$('searchInput').value.trim().toLowerCase(); const records=getRecords().filter(r=>(r.title+r.text).toLowerCase().includes(query)); $('historyCount').textContent=getRecords().length; $('historyList').innerHTML=records.length?records.map(r=>`<article class="history-card" data-id="${r.id}"><strong>${esc(r.title)}</strong><time>${new Date(r.createdAt).toLocaleString('zh-CN')} · ${formatTime(r.duration||0)}</time><p>${esc(r.text.slice(0,100))}</p><div class="card-actions"><button data-action="view">查看</button><button data-action="export">导出</button><button data-action="delete">删除</button></div></article>`).join(''):'<div class="history-empty">没有匹配的会议记录</div>'; }
  function exportRecord(r){ const blob=new Blob([`会议：${r.title}\n时间：${new Date(r.createdAt).toLocaleString('zh-CN')}\n时长：${formatTime(r.duration||0)}\n\n${r.text}`],{type:'text/plain;charset=utf-8'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${r.title||'会议记录'}.txt`;a.click();URL.revokeObjectURL(a.href); }
  function showToast(text){ const el=$('toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400); }
  $('startBtn').onclick=start; $('pauseBtn').onclick=pause; $('stopBtn').onclick=()=>stop(true); $('newBtn').onclick=newMeeting; $('clearTextBtn').onclick=()=>{if(confirm('确定清空当前文字吗？')){state.finalText='';state.interim='';renderText()}}; $('searchInput').oninput=renderHistory; title.onblur=()=>{if(!title.textContent.trim())title.textContent='未命名会议'};
  $('historyList').onclick=e=>{ const card=e.target.closest('.history-card'); if(!card)return; const r=getRecords().find(x=>String(x.id)===card.dataset.id); if(!r)return; const action=e.target.dataset.action; if(action==='delete'){saveRecords(getRecords().filter(x=>x.id!==r.id));renderHistory();showToast('记录已删除')} else if(action==='export')exportRecord(r); else {state.finalText=r.text;title.textContent=r.title;state.elapsed=r.duration||0;$('timer').textContent=formatTime(state.elapsed);renderText();window.scrollTo({top:0,behavior:'smooth'})} };
  $('importBtn').onclick=()=>$('importFile').click(); $('importFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data))throw Error();saveRecords([...data,...getRecords()]);renderHistory();showToast('记录导入成功')}catch(_){showToast('导入失败：文件格式不正确')}};reader.readAsText(file);e.target.value=''};
  if(!supported) $('browserNotice').textContent='当前浏览器不支持语音识别，请使用最新版 Chrome 或 Edge。'; renderText();renderHistory();
})();
